//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.Linq.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.Linq.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bucket translation failed during {0} call. 的本地化字符串。
        /// </summary>
        internal static string BucketTranslationFailed {
            get {
                return ResourceManager.GetString("BucketTranslationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct join expression is not supported yet. 的本地化字符串。
        /// </summary>
        internal static string DirectJoinNotSupported {
            get {
                return ResourceManager.GetString("DirectJoinNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no item in the collection. 的本地化字符串。
        /// </summary>
        internal static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are multiple element in the collection, use First instead. 的本地化字符串。
        /// </summary>
        internal static string MultipleElementInColleciton {
            get {
                return ResourceManager.GetString("MultipleElementInColleciton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There can only be one unique property under {0}. 的本地化字符串。
        /// </summary>
        internal static string MustbeOneUniqueField {
            get {
                return ResourceManager.GetString("MustbeOneUniqueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must contains valid settings information to process. 的本地化字符串。
        /// </summary>
        internal static string MustContainValidSettingsXml {
            get {
                return ResourceManager.GetString("MustContainValidSettingsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must deifne a cotnainer and behavior of each node. 的本地化字符串。
        /// </summary>
        internal static string MustDefineAContainer {
            get {
                return ResourceManager.GetString("MustDefineAContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity class must have a default constructor. 的本地化字符串。
        /// </summary>
        internal static string MustHaveADefaultConstructor {
            get {
                return ResourceManager.GetString("MustHaveADefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must provide a valid callback method. 的本地化字符串。
        /// </summary>
        internal static string MustProvideACallback {
            get {
                return ResourceManager.GetString("MustProvideACallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown expression node type 的本地化字符串。
        /// </summary>
        internal static string UnknowNodeType {
            get {
                return ResourceManager.GetString("UnknowNodeType", resourceCulture);
            }
        }
    }
}
